version: "3.7"
services:
  web:
    build: .
    volumes:
      - .:/var/www/html
    ports:
      - 8080:80
  db:
    image: mysql
    volumes:
      - ./db_data:/var/lib/mysql
      - ./SQL:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: 12345
      MYSQL_DATABASE: docker_database
    ports:
      - 3306:3306
